#!/usr/bin/env python3
# Copyright (c) 2026 Truestock
# SPDX-License-Identifier: MIT

"""Regenerates generated/models.py from the canonical spec at the commit
pinned in spec.lock.json. Generated output is committed, so consumers of
this repo never run the generator.

To move to a newer contract: update spec.lock.json, run this, commit both
spec.lock.json and generated/.

Models are pydantic v2, produced by datamodel-code-generator rather than
openapi-python-client — see the "Tooling ruling" note in the build plan and
in the README's Regenerating section: openapi-python-client only emits attrs
dataclasses, and this SDK's stack commits to pydantic v2.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent


def _fix_self_named_field_type_clash(text: str) -> str:
    """Pydantic v2 refuses a field whose name is textually identical to its
    own bare type annotation (``date: date``) — see
    https://errors.pydantic.dev/2.13/u/unevaluable-type-annotation. The spec
    has exactly one such field (``MarketStatus.date: date``); this generator
    has no flag for it, so the fix is a small, deterministic, documented
    rewrite here rather than a one-off hand-edit of the generated file: alias
    the import and reference the alias only in that field's own annotation,
    leaving the field name and every other use of the type untouched.

    Deliberately narrow: only a line that is *exactly* a field declaration of
    the form ``    <name>: <name> = ...`` (field name equals its bare type)
    is touched, so prose in docstrings/examples containing the word "date"
    is never at risk.
    """
    field_line = re.compile(r"^(\s{4})(\w+): (\w+)(( = .*)?)$", re.MULTILINE)

    clashing_types = set()
    for match in field_line.finditer(text):
        _indent, field_name, type_name, _rest, _default = match.groups()
        if field_name == type_name:
            clashing_types.add(type_name)

    for type_name in clashing_types:
        alias = f"_{type_name.capitalize()}Type"

        # Leave the original import alone — other fields may legitimately use
        # the bare type name (e.g. Expiry.expiry: date), and renaming the
        # import would break every one of those. Instead add a standalone
        # module-level alias right after the import block.
        text = re.sub(
            rf"^(from [\w.]+ import [^\n]*\b{type_name}\b[^\n]*\n)",
            rf"\g<1>{alias} = {type_name}\n",
            text,
            count=1,
            flags=re.MULTILINE,
        )

        # Rewrite only the clashing field's own annotation, matched with the
        # same narrow line pattern used to find it.
        text = re.sub(
            rf"^(\s{{4}}){type_name}: {type_name}(( = .*)?)$",
            rf"\g<1>{type_name}: {alias}\g<2>",
            text,
            flags=re.MULTILINE,
        )
    return text


def main() -> None:
    lock = json.loads((ROOT / "spec.lock.json").read_text(encoding="utf-8"))
    spec_repo = (ROOT / lock["repo"]).resolve()

    # Read the spec AT THE PINNED COMMIT, not from the working tree — a dirty
    # spec checkout must never leak into generated types.
    spec_text = subprocess.run(
        ["git", "-C", str(spec_repo), "show", f"{lock['commit']}:{lock['file']}"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout

    generated_dir = ROOT / "src" / "high_openapi" / "generated"
    generated_dir.mkdir(parents=True, exist_ok=True)
    spec_path = generated_dir / "openapi.json"
    spec_path.write_text(spec_text, encoding="utf-8")

    models_path = generated_dir / "models.py"
    subprocess.run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(spec_path),
            "--input-file-type",
            "openapi",
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--output",
            str(models_path),
            "--target-python-version",
            "3.9",
            "--openapi-scopes",
            "schemas",
            "paths",
            "--use-schema-description",
            "--use-operation-id-as-name",
        ],
        check=True,
    )

    # datamodel-code-generator writes its own header; append the licence
    # header the licence test requires of every hand-written file — this one
    # is generated, so the header is added by this script rather than
    # counting as hand-editing the output.
    header = "# Copyright (c) 2026 Truestock\n# SPDX-License-Identifier: MIT\n# Generated by datamodel-code-generator. DO NOT EDIT BY HAND.\n# Run scripts/regenerate.py to update, after bumping spec.lock.json.\n\n"
    text = header + models_path.read_text(encoding="utf-8")
    text = _fix_self_named_field_type_clash(text)
    models_path.write_text(text, encoding="utf-8")

    print(f"Generated from spec commit {lock['commit'][:7]}.")


if __name__ == "__main__":
    main()
